### ISSUE TITLE
port chart-heapster to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-heapster#2]
- [ ]  Follow [instructions](https://github.com/samsung-cnct/solas/blob/master/docs/gitlab.md) to create and edit`.gitlab-ci.yml` from [template](https://github.com/samsung-cnct/solas-chart/blob/master/.gitlab-ci.yml)
- [ ] also create `build/build.sh` and `build/test.sh` according to instructions
- [ ] make them both executable
- [ ] create secret variable in gitlab
- [ ] add pipeline status badge to README
- [ ] Remove the `build/Jenkinsfile` in the current repo.
- [ ] When PR has merged, make sure that new image is being created on quay. Afterwards,  please head back to the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89) and check off the `chart-heapster`

**Comment by oneilcin** [comment]
https://github.com/samsung-cnct/chart-heapster/pull/3
